export enum PixelFormat {
  YUV = 'yuv',
  RGB = 'rgb',
  UNKNOWN = 'unknown'
}

export enum VideoStabilizationMode {
  OFF = "off",
  auto = "auto",
  STANDARD = "standard",
  CINEMATIC = "cinematic",
  CINEMATIC_EXTENDED = "cinematic-extended"
}

export enum QualityBalance {
  SPEED = "speed",
  BALANCED = "balanced",
  QUALITY = "quality"
}

export enum Torch {
  OFF = "off",
  ON = "on"
}

export enum Orientation {
  PORTRAIT = "portrait",
  LANDSCAPE_RIGHT = "landscape-right",
  PORTRAIT_UPSIDE_DOWN = "portrait-upside-down",
  LANDSCAPE_LEFT = "landscape-left"
}

export enum PreviewViewType {
  SURFACE_VIEW="surface-view",
  TEXTURE_VIEW="texture-view"
}

export enum ResizeMode {
  COVER="cover",
  CONTAIN="contain"
}


